package cli

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/kaessert/crossplane-update-tester/internal/manifest"
	"github.com/kaessert/crossplane-update-tester/internal/validator"
)

// matcherReuseTypesSrc mirrors provider-f5xc's REAL
// ServicePolicyRuleParameters.DomainMatcher / ServicePolicyRuleObservation.DomainMatcher
// shape (apis/cluster/servicepolicyrule/v1alpha1/zz_service_policy_rules_types.go),
// one of the 586 real nested-composite cases this ticket's design comment
// measured: PolicyMatcherTypeBasic is referenced UNCHANGED from both
// Parameters and Observation, with no PolicyMatcherTypeBasicObservation
// companion declared anywhere — the reuse-layout fallback in
// resolveObservationFieldsForKindField, not its faster
// "<Type>Observation" path. regexValues carries no omitempty, exactly the
// real defect shape an incomplete expect: block hits in production.
const matcherReuseTypesSrc = `// Code generated by openapi2crd. DO NOT EDIT.
package v1alpha1

// PolicyMatcherTypeBasic is referenced, unchanged, from both sides — no
// PolicyMatcherTypeBasicObservation companion exists anywhere.
type PolicyMatcherTypeBasic struct {
	ExactValues []string ` + "`json:\"exactValues,omitempty\"`" + `
	RegexValues []string ` + "`json:\"regexValues\"`" + `
}

type ServicePolicyRuleParameters struct {
	Description *string ` + "`json:\"description,omitempty\"`" + `
	// +optional
	DomainMatcher *PolicyMatcherTypeBasic ` + "`json:\"domainMatcher,omitempty\"`" + `
}

// ServicePolicyRuleObservation mirrors DomainMatcher via the identical
// reused PolicyMatcherTypeBasic type.
type ServicePolicyRuleObservation struct {
	// +optional
	DomainMatcher *PolicyMatcherTypeBasic ` + "`json:\"domainMatcher,omitempty\"`" + `
}
`

// allOmitemptyTypesSrc gives every Observation member omitempty, so the
// skeleton for its one nested-composite field is legitimately empty — a
// distinct, valid outcome from an unresolvable field, and this fixture
// pins it.
const allOmitemptyTypesSrc = `// Code generated by openapi2crd. DO NOT EDIT.
package v1alpha1

type WidgetSettings struct {
	Label string ` + "`json:\"label,omitempty\"`" + `
}

type WidgetSettingsObservation struct {
	Label string ` + "`json:\"label,omitempty\"`" + `
}

type WidgetParameters struct {
	Settings *WidgetSettings ` + "`json:\"settings,omitempty\"`" + `
}
`

func writeSkeletonFixture(t *testing.T, name, contents string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), name)
	if err := os.WriteFile(path, []byte(contents), 0o600); err != nil {
		t.Fatalf("writing fixture %s: %v", name, err)
	}
	return path
}

// TestBuildExpectSkeletonMatchesIncompleteExpectationKeysComputation is the
// end-to-end proof this ticket's acceptance criteria require: parse a real
// (mirrored) nested-composite case, emit a skeleton, and confirm the key set
// matches validator.CheckIncompleteExpectations' own computation — driven
// here by a deliberately-incomplete expect: (one that names neither
// key, the maximally incomplete case) — independently of BuildExpectSkeleton's
// internals.
//
// It also pins the concrete key list by name, rather than only cross-checking
// against the other call, so a change that breaks BOTH computations
// identically (e.g. reusing the wrong field) cannot slip past silently.
func TestBuildExpectSkeletonMatchesIncompleteExpectationKeysComputation(t *testing.T) {
	path := writeSkeletonFixture(t, "service_policy_rule_reuse_types.go", matcherReuseTypesSrc)

	got, err := BuildExpectSkeleton(path, "ServicePolicyRule", "domainMatcher")
	if err != nil {
		t.Fatalf("BuildExpectSkeleton: %v", err)
	}

	// Pin the real defect shape directly: exactValues carries omitempty,
	// regexValues does not, so only regexValues is a required key.
	want := []string{"regexValues"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("BuildExpectSkeleton() = %v, want %v", got, want)
	}

	// Independently reproduce validator's own computation via a
	// deliberately-incomplete expect: (empty — the maximally incomplete
	// case) and confirm it reports the identical key set.
	fields, err := validator.ParseGoTypes(path, "ServicePolicyRule")
	if err != nil {
		t.Fatalf("ParseGoTypes: %v", err)
	}
	m := &manifest.Manifest{
		Kind: "ServicePolicyRule",
		Tests: []manifest.UpdateTest{
			{
				Field:  "domainMatcher",
				Value:  map[string]interface{}{"exactValues": []interface{}{"example.com"}},
				Expect: map[string]interface{}{}, // deliberately incomplete: names neither key
			},
		},
	}
	findings := validator.CheckIncompleteExpectations(path, fields, m)
	if len(findings) != 1 {
		t.Fatalf("CheckIncompleteExpectations: got %d findings, want 1: %+v", len(findings), findings)
	}
	if !reflect.DeepEqual(findings[0].Keys, got) {
		t.Errorf("BuildExpectSkeleton() = %v diverges from CheckIncompleteExpectations' own computation %v", got, findings[0].Keys)
	}
}

// TestBuildExpectSkeletonUnknownFieldErrors confirms a field absent from the
// Parameters struct is a clear error, not a silently-empty skeleton.
func TestBuildExpectSkeletonUnknownFieldErrors(t *testing.T) {
	path := writeSkeletonFixture(t, "service_policy_rule_reuse_types.go", matcherReuseTypesSrc)

	_, err := BuildExpectSkeleton(path, "ServicePolicyRule", "noSuchField")
	if err == nil {
		t.Fatal("BuildExpectSkeleton: got nil error, want one naming the unknown field")
	}
	if !strings.Contains(err.Error(), "noSuchField") {
		t.Errorf("error %q does not name the unresolved field", err.Error())
	}
}

// TestBuildExpectSkeletonUnknownKindErrors confirms a types file that does
// not declare the requested {kind}Parameters struct at all is also a clear
// error.
func TestBuildExpectSkeletonUnknownKindErrors(t *testing.T) {
	path := writeSkeletonFixture(t, "service_policy_rule_reuse_types.go", matcherReuseTypesSrc)

	_, err := BuildExpectSkeleton(path, "NoSuchKind", "domainMatcher")
	if err == nil {
		t.Fatal("BuildExpectSkeleton: got nil error, want one naming the unresolved struct")
	}
}

// TestBuildExpectSkeletonAllOmitemptyYieldsNoKeys pins the legitimate
// zero-keys outcome — every Observation member carries omitempty, so no
// expect: block is required at all — distinct from an error.
func TestBuildExpectSkeletonAllOmitemptyYieldsNoKeys(t *testing.T) {
	path := writeSkeletonFixture(t, "widget_types.go", allOmitemptyTypesSrc)

	got, err := BuildExpectSkeleton(path, "Widget", "settings")
	if err != nil {
		t.Fatalf("BuildExpectSkeleton: unexpected error: %v", err)
	}
	if len(got) != 0 {
		t.Errorf("BuildExpectSkeleton() = %v, want no keys", got)
	}
}

// TestFormatExpectSkeletonPlaceholdersAreLabelled confirms the rendered
// block never prints anything that could be mistaken for a resolved value —
// every key gets the same, obviously-fake placeholder.
func TestFormatExpectSkeletonPlaceholdersAreLabelled(t *testing.T) {
	got := FormatExpectSkeleton([]string{"regexValues", "exactValues"})
	want := "  exactValues: " + ExpectSkeletonPlaceholder + "\n" +
		"  regexValues: " + ExpectSkeletonPlaceholder + "\n"
	if got != want {
		t.Errorf("FormatExpectSkeleton() = %q, want %q", got, want)
	}
}

// TestFormatExpectSkeletonEmptyKeysRendersEmpty confirms an empty key slice
// renders to the empty string rather than an empty "expect:" stanza a
// caller might mistake for a real, resolved entry.
func TestFormatExpectSkeletonEmptyKeysRendersEmpty(t *testing.T) {
	if got := FormatExpectSkeleton(nil); got != "" {
		t.Errorf("FormatExpectSkeleton(nil) = %q, want empty string", got)
	}
}

// TestPrintExpectSkeletonDoesNotPanic is a smoke test for the output
// formatter, matching the convention of the validator package's own
// Print*DoesNotPanic tests.
func TestPrintExpectSkeletonDoesNotPanic(t *testing.T) {
	var b strings.Builder
	PrintExpectSkeleton(&b, "domainMatcher", nil)
	if !strings.Contains(b.String(), "domainMatcher") {
		t.Errorf("PrintExpectSkeleton with no keys did not name the field: %q", b.String())
	}

	b.Reset()
	PrintExpectSkeleton(&b, "domainMatcher", []string{"regexValues"})
	if !strings.Contains(b.String(), "regexValues") || !strings.Contains(b.String(), ExpectSkeletonPlaceholder) {
		t.Errorf("PrintExpectSkeleton with keys did not render key/placeholder: %q", b.String())
	}
}

// TestBuildExpectSkeletonListOfObjectsField confirms a list-typed
// nested-composite field ([]RuleMatcher) resolves the same key set a
// singular object field would — the synthetic entry's representative empty
// object stands in for one list element, mirroring
// CheckIncompleteExpectations' own asObjects handling.
func TestBuildExpectSkeletonListOfObjectsField(t *testing.T) {
	const src = `// Code generated by openapi2crd. DO NOT EDIT.
package v1alpha1

type RuleMatcher struct {
	ExactValues []string ` + "`json:\"exactValues,omitempty\"`" + `
	RegexValues []string ` + "`json:\"regexValues,omitempty\"`" + `
}

type RuleMatcherObservation struct {
	ExactValues []string ` + "`json:\"exactValues,omitempty\"`" + `
	RegexValues []string ` + "`json:\"regexValues\"`" + `
}

type ListyParameters struct {
	Matchers []RuleMatcher ` + "`json:\"matchers\"`" + `
}
`
	path := writeSkeletonFixture(t, "listy_types.go", src)

	got, err := BuildExpectSkeleton(path, "Listy", "matchers")
	if err != nil {
		t.Fatalf("BuildExpectSkeleton: %v", err)
	}
	want := []string{"regexValues"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("BuildExpectSkeleton() = %v, want %v", got, want)
	}
}
