package validator

import (
	"reflect"
	"sort"
	"testing"

	"github.com/kaessert/crossplane-update-tester/internal/manifest"
)

// matcherTypesSrc exercises the SPLIT layout — a distinct
// "<Type>Observation" companion struct — via the fast path in
// resolveObservationFieldsForKindField. It intentionally declares
// PolicyMatcherTypeBasicObservation as a SEPARATE struct from
// PolicyMatcherTypeBasic to pin that fast path; provider-f5xc's REAL
// ServicePolicyRuleParameters.DomainMatcher does not have a separate
// Observation companion at all — see matcherReuseTypesSrc below for that
// shape, and TestCheckIncompleteExpectationsReusedObservationStructFlagged
// for the fallback path it exercises.
const matcherTypesSrc = `// Code generated by openapi2crd. DO NOT EDIT.
package v1alpha1

// PolicyMatcherTypeBasic is a match predicate on a request field.
type PolicyMatcherTypeBasic struct {
	ExactValues []string ` + "`json:\"exactValues,omitempty\"`" + `
	RegexValues []string ` + "`json:\"regexValues,omitempty\"`" + `
}

// PolicyMatcherTypeBasicObservation is the Observation-only variant.
// exactValues carries omitempty; regexValues does not — the shape the real
// defect was measured on.
type PolicyMatcherTypeBasicObservation struct {
	ExactValues []string ` + "`json:\"exactValues,omitempty\"`" + `
	RegexValues []string ` + "`json:\"regexValues\"`" + `
}

// ServicePolicyRuleParameters are the configurable fields of a
// ServicePolicyRule.
type ServicePolicyRuleParameters struct {
	Description *string ` + "`json:\"description,omitempty\"`" + `
	// +optional
	DomainMatcher *PolicyMatcherTypeBasic ` + "`json:\"domainMatcher,omitempty\"`" + `
	// +optional
	BodyMatcher *PolicyMatcherTypeBasic ` + "`json:\"bodyMatcher,omitempty\"`" + `
}
`

// matcherReuseTypesSrc mirrors provider-f5xc's REAL
// ServicePolicyRuleParameters.DomainMatcher /
// ServicePolicyRuleObservation.DomainMatcher shape
// (apis/cluster/servicepolicyrule/v1alpha1/zz_service_policy_rules_types.go):
// PolicyMatcherTypeBasic is referenced UNCHANGED from both Parameters and
// Observation, with no PolicyMatcherTypeBasicObservation companion declared
// anywhere in the package. regexValues carries no omitempty, exactly the
// real defect shape (unsatisfiable expect: block once exactValues alone is
// named).
const matcherReuseTypesSrc = `// Code generated by openapi2crd. DO NOT EDIT.
package v1alpha1

// PolicyMatcherTypeBasic is referenced, unchanged, from both sides — no
// PolicyMatcherTypeBasicObservation companion exists anywhere.
type PolicyMatcherTypeBasic struct {
	ExactValues []string ` + "`json:\"exactValues,omitempty\"`" + `
	RegexValues []string ` + "`json:\"regexValues\"`" + `
}

type ServicePolicyRuleParameters struct {
	Description *string ` + "`json:\"description,omitempty\"`" + `
	// +optional
	DomainMatcher *PolicyMatcherTypeBasic ` + "`json:\"domainMatcher,omitempty\"`" + `
}

// ServicePolicyRuleObservation mirrors DomainMatcher via the identical
// reused PolicyMatcherTypeBasic type.
type ServicePolicyRuleObservation struct {
	// +optional
	DomainMatcher *PolicyMatcherTypeBasic ` + "`json:\"domainMatcher,omitempty\"`" + `
}
`

const kindServicePolicyRule = "ServicePolicyRule"

// matcherFixture writes the matcher types fixture once and returns both its
// path and the parsed ServicePolicyRuleParameters fields.
func matcherFixture(t *testing.T) (path string, fields []FieldInfo) {
	t.Helper()
	path = writeFixture(t, "service_policy_rule_types.go", matcherTypesSrc)
	fields, err := ParseGoTypes(path, kindServicePolicyRule)
	if err != nil {
		t.Fatalf("ParseGoTypes: %v", err)
	}
	return path, fields
}

// matcherReuseFixture writes the REUSE-layout fixture (matcherReuseTypesSrc)
// once and returns both its path and the parsed ServicePolicyRuleParameters
// fields.
func matcherReuseFixture(t *testing.T) (path string, fields []FieldInfo) {
	t.Helper()
	path = writeFixture(t, "service_policy_rule_reuse_types.go", matcherReuseTypesSrc)
	fields, err := ParseGoTypes(path, kindServicePolicyRule)
	if err != nil {
		t.Fatalf("ParseGoTypes: %v", err)
	}
	return path, fields
}

// TestCheckIncompleteExpectationsReusedObservationStructFlagged is the
// positive control for the reuse layout, resolved via
// resolveObservationFieldsForKindField's fallback rather than its
// "<Type>Observation" fast path: domainMatcher's declared type,
// PolicyMatcherTypeBasic, has no separate Observation companion anywhere in
// matcherReuseTypesSrc, exactly like the real
// ServicePolicyRuleParameters.DomainMatcher / ServicePolicyRuleObservation
// pair in provider-f5xc's zz_service_policy_rules_types.go. Naming only
// exactValues in the expectation must still flag the non-omitempty
// regexValues sibling.
func TestCheckIncompleteExpectationsReusedObservationStructFlagged(t *testing.T) {
	path, fields := matcherReuseFixture(t)

	m := &manifest.Manifest{
		Kind: kindServicePolicyRule,
		Tests: []manifest.UpdateTest{
			{
				Field: "domainMatcher",
				Value: map[string]interface{}{"exactValues": []interface{}{"example.com"}},
			},
		},
	}

	findings := CheckIncompleteExpectations(path, fields, m)
	if len(findings) != 1 {
		t.Fatalf("got %d findings, want 1: %+v", len(findings), findings)
	}
	if findings[0].Field != "domainMatcher" {
		t.Errorf("Field = %q, want domainMatcher", findings[0].Field)
	}
	if len(findings[0].Keys) != 1 || findings[0].Keys[0] != "regexValues" {
		t.Errorf("Keys = %v, want [regexValues]", findings[0].Keys)
	}
}

// TestCheckIncompleteExpectationsReusedObservationStructCompleteExpectNotFlagged
// confirms the reuse-layout fallback's own fix — an expect: block naming
// regexValues — passes clean, matching
// TestCheckIncompleteExpectationsCompleteExpectNotFlagged's split-layout
// case.
func TestCheckIncompleteExpectationsReusedObservationStructCompleteExpectNotFlagged(t *testing.T) {
	path, fields := matcherReuseFixture(t)

	m := &manifest.Manifest{
		Kind: kindServicePolicyRule,
		Tests: []manifest.UpdateTest{
			{
				Field: "domainMatcher",
				Value: map[string]interface{}{"exactValues": []interface{}{"example.com"}},
				Expect: map[string]interface{}{
					"exactValues": []interface{}{"example.com"},
					"regexValues": nil,
				},
			},
		},
	}

	findings := CheckIncompleteExpectations(path, fields, m)
	if len(findings) != 0 {
		t.Errorf("got %d findings, want 0 (expect: already names regexValues): %+v", len(findings), findings)
	}
}

// TestCheckIncompleteExpectationsFieldAbsentFromCreateTimeFlagged pins the
// real-world domainMatcher shape (979c6840 Finding 1): the field is absent
// from spec.forProvider entirely at create time (first-time set), so
// CheckMergePatchSiblings' merge-patch simulation has nothing to find
// "surviving" — this check must still catch the missing non-omitempty
// regexValues sibling.
func TestCheckIncompleteExpectationsFieldAbsentFromCreateTimeFlagged(t *testing.T) {
	path, fields := matcherFixture(t)

	m := &manifest.Manifest{
		Kind: kindServicePolicyRule,
		Tests: []manifest.UpdateTest{
			{
				Field: "domainMatcher",
				Value: map[string]interface{}{"exactValues": []interface{}{"example.com"}},
			},
		},
	}

	findings := CheckIncompleteExpectations(path, fields, m)
	if len(findings) != 1 {
		t.Fatalf("got %d findings, want 1: %+v", len(findings), findings)
	}
	if findings[0].Field != "domainMatcher" {
		t.Errorf("Field = %q, want domainMatcher", findings[0].Field)
	}
	if len(findings[0].Keys) != 1 || findings[0].Keys[0] != "regexValues" {
		t.Errorf("Keys = %v, want [regexValues]", findings[0].Keys)
	}
}

// TestCheckIncompleteExpectationsIgnoreMapKeysExemptsMemberNotFlagged is the
// same shape as TestCheckIncompleteExpectationsFieldAbsentFromCreateTimeFlagged
// — the same missing non-omitempty regexValues sibling — except the entry
// also names regexValues in its own ignoreMapKeys, which must exempt it from
// this check exactly as an expect:-named key already does — see
// manifest.UpdateTest.IgnoreMapKeys.
func TestCheckIncompleteExpectationsIgnoreMapKeysExemptsMemberNotFlagged(t *testing.T) {
	path, fields := matcherFixture(t)

	m := &manifest.Manifest{
		Kind: kindServicePolicyRule,
		Tests: []manifest.UpdateTest{
			{
				Field:         "domainMatcher",
				Value:         map[string]interface{}{"exactValues": []interface{}{"example.com"}},
				IgnoreMapKeys: []string{"regexValues"},
			},
		},
	}

	findings := CheckIncompleteExpectations(path, fields, m)
	if len(findings) != 0 {
		t.Errorf("got %d findings, want 0 (ignoreMapKeys names regexValues): %+v", len(findings), findings)
	}
}

// TestCheckIncompleteExpectationsSiblingSurvivesNotDoubleFlagged pins the
// bodyMatcher shape: the field IS present at create time with both siblings,
// so CheckMergePatchSiblings' own SIBLING-SURVIVES finding already covers
// the missing regexValues key under its own label. This check must not
// re-report it a second time.
func TestCheckIncompleteExpectationsSiblingSurvivesNotDoubleFlagged(t *testing.T) {
	path, fields := matcherFixture(t)

	m := &manifest.Manifest{
		Kind: kindServicePolicyRule,
		ForProvider: map[string]interface{}{
			"bodyMatcher": map[string]interface{}{
				"exactValues": []interface{}{},
				"regexValues": []interface{}{},
			},
		},
		Tests: []manifest.UpdateTest{
			{
				Field: "bodyMatcher",
				Value: map[string]interface{}{"exactValues": []interface{}{"updated"}},
			},
		},
	}

	// Sanity: CheckMergePatchSiblings does independently flag regexValues
	// for this exact entry — confirming the scenario actually reproduces
	// the "already caught" precondition this test exists to exercise.
	siblingFindings := CheckMergePatchSiblings(m)
	if len(siblingFindings) != 1 || len(siblingFindings[0].Keys) != 1 || siblingFindings[0].Keys[0] != "regexValues" {
		t.Fatalf("precondition failed: CheckMergePatchSiblings = %+v, want a single regexValues finding", siblingFindings)
	}

	findings := CheckIncompleteExpectations(path, fields, m)
	if len(findings) != 0 {
		t.Errorf("got %d findings, want 0 (already reported as SIBLING-SURVIVES): %+v", len(findings), findings)
	}
}

// TestCheckIncompleteExpectationsCompleteExpectNotFlagged confirms an
// expect: block already naming every non-omitempty sibling is not flagged —
// the fix this check exists to push implementers toward must itself pass
// clean.
func TestCheckIncompleteExpectationsCompleteExpectNotFlagged(t *testing.T) {
	path, fields := matcherFixture(t)

	m := &manifest.Manifest{
		Kind: kindServicePolicyRule,
		Tests: []manifest.UpdateTest{
			{
				Field: "domainMatcher",
				Value: map[string]interface{}{"exactValues": []interface{}{"example.com"}},
				Expect: map[string]interface{}{
					"exactValues": []interface{}{"example.com"},
					"regexValues": nil,
				},
			},
		},
	}

	findings := CheckIncompleteExpectations(path, fields, m)
	if len(findings) != 0 {
		t.Errorf("got %d findings, want 0 (expect: already names regexValues): %+v", len(findings), findings)
	}
}

// TestCheckIncompleteExpectationsOmitemptySiblingNotFlagged confirms a
// sibling that DOES carry omitempty on the Observation struct is never
// flagged, whether or not it appears in the expectation — omitempty means
// the field is dropped from the marshaled object entirely when unset, so
// there is no null-mismatch hazard.
func TestCheckIncompleteExpectationsOmitemptySiblingNotFlagged(t *testing.T) {
	path, fields := matcherFixture(t)

	m := &manifest.Manifest{
		Kind: kindServicePolicyRule,
		Tests: []manifest.UpdateTest{
			{
				Field:  "domainMatcher",
				Value:  map[string]interface{}{"regexValues": []interface{}{"^example\\."}},
				Expect: map[string]interface{}{"regexValues": []interface{}{"^example\\."}},
			},
		},
	}

	findings := CheckIncompleteExpectations(path, fields, m)
	if len(findings) != 0 {
		t.Errorf("got %d findings, want 0 (exactValues carries omitempty): %+v", len(findings), findings)
	}
}

// TestCheckIncompleteExpectationsSkipEntryNotFlagged confirms a skip: entry
// is never flagged, even though its value would otherwise omit a
// non-omitempty sibling.
func TestCheckIncompleteExpectationsSkipEntryNotFlagged(t *testing.T) {
	path, fields := matcherFixture(t)

	m := &manifest.Manifest{
		Kind: kindServicePolicyRule,
		Tests: []manifest.UpdateTest{
			{
				Field: "domainMatcher",
				Skip:  manifest.LegacySkip("not exercised in this example"),
				Value: map[string]interface{}{"exactValues": []interface{}{"example.com"}},
			},
		},
	}

	findings := CheckIncompleteExpectations(path, fields, m)
	if len(findings) != 0 {
		t.Errorf("got %d findings, want 0 for a skip: entry: %+v", len(findings), findings)
	}
}

// TestCheckIncompleteExpectationsScalarNotFlagged confirms a plain scalar
// expectation is left alone — this check only reasons about object/
// list-of-object shapes, matching CheckObservability.
func TestCheckIncompleteExpectationsScalarNotFlagged(t *testing.T) {
	path, fields := matcherFixture(t)

	m := &manifest.Manifest{
		Kind: kindServicePolicyRule,
		Tests: []manifest.UpdateTest{
			{Field: "description", Value: "updated by uptest"},
		},
	}

	findings := CheckIncompleteExpectations(path, fields, m)
	if len(findings) != 0 {
		t.Errorf("got %d findings, want 0 for a scalar field: %+v", len(findings), findings)
	}
}

// TestCheckIncompleteExpectationsDottedFieldNotFlagged confirms a dotted
// field path is left unflagged — resolving a nested field's own nested
// struct is out of scope, matching CheckObservability.
func TestCheckIncompleteExpectationsDottedFieldNotFlagged(t *testing.T) {
	path, fields := matcherFixture(t)

	m := &manifest.Manifest{
		Kind: kindServicePolicyRule,
		Tests: []manifest.UpdateTest{
			{
				Field: "domainMatcher.exactValues",
				Value: []interface{}{"example.com"},
			},
		},
	}

	findings := CheckIncompleteExpectations(path, fields, m)
	if len(findings) != 0 {
		t.Errorf("got %d findings, want 0 for a dotted field path: %+v", len(findings), findings)
	}
}

// TestCheckIncompleteExpectationsUnresolvableObservationNotFlagged confirms
// a field whose nested struct has no "<Type>Observation" companion anywhere
// is left unflagged rather than guessed at.
func TestCheckIncompleteExpectationsUnresolvableObservationNotFlagged(t *testing.T) {
	const src = `// Code generated by openapi2crd. DO NOT EDIT.
package v1alpha1

type NoObservationWidget struct {
	Label *string ` + "`json:\"label,omitempty\"`" + `
}

type GizmoParameters struct {
	Widget *NoObservationWidget ` + "`json:\"widget,omitempty\"`" + `
}
`
	path := writeFixture(t, "gizmo_types.go", src)
	fields, err := ParseGoTypes(path, "Gizmo")
	if err != nil {
		t.Fatalf("ParseGoTypes: %v", err)
	}

	m := &manifest.Manifest{
		Kind: "Gizmo",
		Tests: []manifest.UpdateTest{
			{Field: "widget", Value: map[string]interface{}{"label": "updated"}},
		},
	}

	findings := CheckIncompleteExpectations(path, fields, m)
	if len(findings) != 0 {
		t.Errorf("got %d findings, want 0 when NoObservationWidgetObservation cannot be resolved: %+v", len(findings), findings)
	}
}

// TestCheckIncompleteExpectationsListOfObjectsFlagsPerItem confirms a
// list-of-objects field is checked per item, mirroring
// CheckObservability's asObjects handling.
func TestCheckIncompleteExpectationsListOfObjectsFlagsPerItem(t *testing.T) {
	const src = `// Code generated by openapi2crd. DO NOT EDIT.
package v1alpha1

type RuleMatcher struct {
	ExactValues []string ` + "`json:\"exactValues,omitempty\"`" + `
	RegexValues []string ` + "`json:\"regexValues,omitempty\"`" + `
}

type RuleMatcherObservation struct {
	ExactValues []string ` + "`json:\"exactValues,omitempty\"`" + `
	RegexValues []string ` + "`json:\"regexValues\"`" + `
}

type ListyParameters struct {
	Matchers []RuleMatcher ` + "`json:\"matchers\"`" + `
}
`
	path := writeFixture(t, "listy_types.go", src)
	fields, err := ParseGoTypes(path, "Listy")
	if err != nil {
		t.Fatalf("ParseGoTypes: %v", err)
	}

	m := &manifest.Manifest{
		Kind: "Listy",
		Tests: []manifest.UpdateTest{
			{
				Field: "matchers",
				Value: []interface{}{
					map[string]interface{}{"exactValues": []interface{}{"a"}},
				},
			},
		},
	}

	findings := CheckIncompleteExpectations(path, fields, m)
	if len(findings) != 1 {
		t.Fatalf("got %d findings, want 1: %+v", len(findings), findings)
	}
	if len(findings[0].Keys) != 1 || findings[0].Keys[0] != "regexValues" {
		t.Errorf("Keys = %v, want [regexValues]", findings[0].Keys)
	}
}

// TestMergePatchSiblingKeySet covers the helper in isolation: the two
// preconditions (value: is an object patch, and the field already holds an
// object at create time) both gating an empty result when either fails.
func TestMergePatchSiblingKeySet(t *testing.T) {
	cases := map[string]struct {
		reason      string
		forProvider map[string]interface{}
		test        manifest.UpdateTest
		want        []string
	}{
		"ObjectPatchOntoPopulatedObject": {
			reason: "the ordinary sibling-survival shape",
			forProvider: map[string]interface{}{
				"bodyMatcher": map[string]interface{}{
					"exactValues": []interface{}{},
					"regexValues": []interface{}{},
				},
			},
			test: manifest.UpdateTest{
				Field: "bodyMatcher",
				Value: map[string]interface{}{"exactValues": []interface{}{"updated"}},
			},
			want: []string{"regexValues"},
		},
		"ListValuePatch": {
			reason: "a list-valued patch never gates a sibling set — RFC 7386 replaces it wholesale",
			forProvider: map[string]interface{}{
				"bodyMatcher": map[string]interface{}{"exactValues": []interface{}{}},
			},
			test: manifest.UpdateTest{
				Field: "bodyMatcher",
				Value: []interface{}{"updated"},
			},
			want: nil,
		},
		"FieldAbsentFromForProvider": {
			reason: "a first-time-set field has nothing for the merge-patch simulation to see",
			forProvider: map[string]interface{}{
				"description": "original",
			},
			test: manifest.UpdateTest{
				Field: "domainMatcher",
				Value: map[string]interface{}{"exactValues": []interface{}{"example.com"}},
			},
			want: nil,
		},
	}

	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			got := mergePatchSiblingKeySet(tc.forProvider, tc.test)
			var gotKeys []string
			for k := range got {
				gotKeys = append(gotKeys, k)
			}
			sort.Strings(gotKeys)
			want := append([]string(nil), tc.want...)
			sort.Strings(want)
			if !reflect.DeepEqual(gotKeys, want) {
				t.Errorf("%s: mergePatchSiblingKeySet() keys = %v, want %v", tc.reason, gotKeys, want)
			}
		})
	}
}

// TestPrintIncompleteExpectationsDoesNotPanic is a smoke test for the output
// formatter, matching the convention of PrintValidation's own smoke test.
func TestPrintIncompleteExpectationsDoesNotPanic(t *testing.T) {
	PrintIncompleteExpectations(nil)
	PrintIncompleteExpectations([]IncompleteExpectationFinding{
		{Field: "domainMatcher", Keys: []string{"regexValues"}},
	})
}
