package validator

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/kaessert/crossplane-update-tester/internal/manifest"
)

// gadgetTypesSrc is a synthetic generated-types fixture mirroring the real
// shape this check exists for: a Parameters-side nested reference struct
// (GadgetOwnerRef) whose Observation-only variant (GadgetOwnerRefObservation)
// excludes the input-only *Ref field, exactly like
// SensitiveDataPolicyDataTypeRef / SensitiveDataPolicyDataTypeRefObservation
// in provider-f5xc. GadgetWidget has no matching *Observation companion at
// all, standing in for a nested type this checker cannot resolve.
const gadgetTypesSrc = `// Code generated by openapi2crd. DO NOT EDIT.
package v1alpha1

// GadgetOwnerRef is a compound cross-resource reference.
type GadgetOwnerRef struct {
	Name *string ` + "`json:\"name,omitempty\"`" + `
	OwnerRef *xpv1.Reference ` + "`json:\"ownerRef,omitempty\"`" + `
}

// GadgetOwnerRefObservation is the Observation-only variant of GadgetOwnerRef
// with cross-resource reference fields excluded — input-only, no observed
// state.
type GadgetOwnerRefObservation struct {
	Name *string ` + "`json:\"name,omitempty\"`" + `
}

// GadgetWidget has no Observation companion declared anywhere in this file.
type GadgetWidget struct {
	Label *string ` + "`json:\"label,omitempty\"`" + `
}

// GadgetParameters are the configurable fields of a Gadget.
type GadgetParameters struct {
	Comment *string ` + "`json:\"comment,omitempty\"`" + `
	Owners []GadgetOwnerRef ` + "`json:\"owners\"`" + `
	Widgets []GadgetWidget ` + "`json:\"widgets\"`" + `
}
`

const kindGadget = "Gadget"

// gadgetFixture writes the gadget types fixture once and returns both its
// path and the parsed GadgetParameters fields, so every test below resolves
// nested Observation structs against the exact same file its FieldInfo.GoType
// values were parsed from.
func gadgetFixture(t *testing.T) (path string, fields []FieldInfo) {
	t.Helper()
	path = writeFixture(t, "gadget_types.go", gadgetTypesSrc)
	fields, err := ParseGoTypes(path, kindGadget)
	if err != nil {
		t.Fatalf("ParseGoTypes: %v", err)
	}
	return path, fields
}

// TestCheckObservabilityRefFormNoExpectFlagged is the core regression case:
// a list-of-objects value patches to the reference-only shape with no
// expect:, and the compound reference's Ref field can never appear in the
// generated Observation struct.
func TestCheckObservabilityRefFormNoExpectFlagged(t *testing.T) {
	path, fields := gadgetFixture(t)

	tests := []manifest.UpdateTest{
		{
			Field: "owners",
			Value: []interface{}{
				map[string]interface{}{
					"ownerRef": map[string]interface{}{"name": "foo"},
				},
			},
		},
	}

	findings := CheckObservability(path, fields, tests)
	if len(findings) != 1 {
		t.Fatalf("got %d findings, want 1: %+v", len(findings), findings)
	}
	if findings[0].Field != "owners" {
		t.Errorf("Field = %q, want %q", findings[0].Field, "owners")
	}
	if len(findings[0].Keys) != 1 || findings[0].Keys[0] != "ownerRef" {
		t.Errorf("Keys = %v, want [ownerRef]", findings[0].Keys)
	}
}

// TestCheckObservabilityRefFormWithCorrectExpectNotFlagged confirms an entry
// that already carries a correct expect: (naming only keys the Observation
// struct actually has) is not flagged — the fix this check exists to push
// implementers toward must itself pass clean.
func TestCheckObservabilityRefFormWithCorrectExpectNotFlagged(t *testing.T) {
	path, fields := gadgetFixture(t)

	tests := []manifest.UpdateTest{
		{
			Field: "owners",
			Value: []interface{}{
				map[string]interface{}{
					"ownerRef": map[string]interface{}{"name": "foo"},
				},
			},
			Expect: []interface{}{
				map[string]interface{}{"name": "foo"},
			},
		},
	}

	findings := CheckObservability(path, fields, tests)
	if len(findings) != 0 {
		t.Errorf("got %d findings, want 0 (expect: resolves to an observable shape): %+v", len(findings), findings)
	}
}

// TestCheckObservabilitySkipEntryNotFlagged confirms a skip: entry is never
// flagged, even though its value would otherwise be unobservable.
func TestCheckObservabilitySkipEntryNotFlagged(t *testing.T) {
	path, fields := gadgetFixture(t)

	tests := []manifest.UpdateTest{
		{
			Field: "owners",
			Skip:  "server always overwrites this list",
			Value: []interface{}{
				map[string]interface{}{
					"ownerRef": map[string]interface{}{"name": "foo"},
				},
			},
		},
	}

	findings := CheckObservability(path, fields, tests)
	if len(findings) != 0 {
		t.Errorf("got %d findings, want 0 for a skip: entry: %+v", len(findings), findings)
	}
}

// TestCheckObservabilityScalarNotFlagged confirms a plain scalar expectation
// is left alone — this check only reasons about object/list-of-object
// shapes.
func TestCheckObservabilityScalarNotFlagged(t *testing.T) {
	path, fields := gadgetFixture(t)

	tests := []manifest.UpdateTest{
		{Field: "comment", Value: "updated by uptest"},
	}

	findings := CheckObservability(path, fields, tests)
	if len(findings) != 0 {
		t.Errorf("got %d findings, want 0 for a scalar field: %+v", len(findings), findings)
	}
}

// TestCheckObservabilityUnresolvableObservationNotFlagged confirms a field
// whose nested struct has no "<Type>Observation" companion anywhere in the
// types file is left unflagged rather than guessed at — the conservative
// default this check promises.
func TestCheckObservabilityUnresolvableObservationNotFlagged(t *testing.T) {
	path, fields := gadgetFixture(t)

	tests := []manifest.UpdateTest{
		{
			Field: "widgets",
			Value: []interface{}{
				map[string]interface{}{"label": "updated"},
			},
		},
	}

	findings := CheckObservability(path, fields, tests)
	if len(findings) != 0 {
		t.Errorf("got %d findings, want 0 when GadgetWidgetObservation cannot be resolved: %+v", len(findings), findings)
	}
}

// TestCheckObservabilityDottedFieldNotFlagged confirms a dotted field path
// is left unflagged — resolving a nested field's own nested struct is out
// of scope for this check.
func TestCheckObservabilityDottedFieldNotFlagged(t *testing.T) {
	path, fields := gadgetFixture(t)

	tests := []manifest.UpdateTest{
		{
			Field: "owners.ownerRef",
			Value: map[string]interface{}{"name": "foo"},
		},
	}

	findings := CheckObservability(path, fields, tests)
	if len(findings) != 0 {
		t.Errorf("got %d findings, want 0 for a dotted field path: %+v", len(findings), findings)
	}
}

// TestCheckObservabilityUnknownFieldNotFlagged confirms a field name absent
// from the Parameters struct entirely is left unflagged by this check — a
// genuinely missing/renamed field is validator.ValidateManifest's job to
// report as MISSING, not this one's.
func TestCheckObservabilityUnknownFieldNotFlagged(t *testing.T) {
	path, fields := gadgetFixture(t)

	tests := []manifest.UpdateTest{
		{
			Field: "doesNotExist",
			Value: []interface{}{
				map[string]interface{}{"ownerRef": map[string]interface{}{"name": "foo"}},
			},
		},
	}

	findings := CheckObservability(path, fields, tests)
	if len(findings) != 0 {
		t.Errorf("got %d findings, want 0 for a field absent from Parameters: %+v", len(findings), findings)
	}
}

// TestCheckObservabilityF5XCSensitiveDataPolicyReproduction pins the exact
// real-world shape this check was written for: SensitiveDataPolicy's
// customDataTypes field, ref-form value with no expect:.
func TestCheckObservabilityF5XCSensitiveDataPolicyReproduction(t *testing.T) {
	const src = `// Code generated by openapi2crd. DO NOT EDIT.
package v1alpha1

type SensitiveDataPolicyDataTypeRef struct {
	Name *string ` + "`json:\"name,omitempty\"`" + `
	Namespace *string ` + "`json:\"namespace,omitempty\"`" + `
	CustomDataTypesRef *xpv2.NamespacedReference ` + "`json:\"customDataTypesRef,omitempty\"`" + `
	CustomDataTypesSelector *xpv2.NamespacedSelector ` + "`json:\"customDataTypesSelector,omitempty\"`" + `
}

type SensitiveDataPolicyDataTypeRefObservation struct {
	Name *string ` + "`json:\"name,omitempty\"`" + `
	Namespace *string ` + "`json:\"namespace,omitempty\"`" + `
}

type SensitiveDataPolicyParameters struct {
	CustomDataTypes []SensitiveDataPolicyDataTypeRef ` + "`json:\"customDataTypes\"`" + `
}
`
	path := writeFixture(t, "sensitive_data_policy_types.go", src)
	fields, err := ParseGoTypes(path, "SensitiveDataPolicy")
	if err != nil {
		t.Fatalf("ParseGoTypes: %v", err)
	}

	tests := []manifest.UpdateTest{
		{
			Field: "customDataTypes",
			Value: []interface{}{
				map[string]interface{}{
					"customDataTypesRef": map[string]interface{}{"name": "xp-example-data-type-ns"},
				},
			},
		},
	}

	findings := CheckObservability(path, fields, tests)
	if len(findings) != 1 {
		t.Fatalf("got %d findings, want 1: %+v", len(findings), findings)
	}
	if findings[0].Field != "customDataTypes" {
		t.Errorf("Field = %q, want customDataTypes", findings[0].Field)
	}
	if len(findings[0].Keys) != 1 || findings[0].Keys[0] != "customDataTypesRef" {
		t.Errorf("Keys = %v, want [customDataTypesRef]", findings[0].Keys)
	}
}

// TestCheckObservabilitySplitFileObservationResolvedFromSibling reproduces
// the real provider-f5xc TCPLoadBalancerParameters.originPoolsWeights shape
// (727629c7 Defect 3): OriginPoolsWeights is []ViewsOriginPoolWithWeight, but
// ViewsOriginPoolWithWeightObservation is declared in a DIFFERENT resource's
// types file within the same flat apis/<scope>/v1alpha1/ package — a MIXED
// layout. Passing only the TCP load balancer's own types file must still
// resolve the Observation companion by searching its zz_*_types.go siblings,
// and a poolRef key (genuinely absent from the real Observation struct) must
// still be caught.
func TestCheckObservabilitySplitFileObservationResolvedFromSibling(t *testing.T) {
	dir := t.TempDir()

	// zz_tcp_loadbalancers_types.go: declares the Parameters struct and the
	// Parameters-side ViewsOriginPoolWithWeight, but NOT its Observation
	// companion — mirroring the real split.
	tcpSrc := `// Code generated by openapi2crd. DO NOT EDIT.
package v1alpha1

type ViewsOriginPoolWithWeight struct {
	PoolRef *xpv1.Reference ` + "`json:\"poolRef,omitempty\"`" + `
	Weight *int64 ` + "`json:\"weight,omitempty\"`" + `
}

type TCPLoadBalancerParameters struct {
	OriginPoolsWeights []ViewsOriginPoolWithWeight ` + "`json:\"originPoolsWeights\"`" + `
}
`
	tcpPath := writeFixtureInDir(t, dir, "zz_tcp_loadbalancers_types.go", tcpSrc)

	// zz_http_loadbalancers_types.go: a sibling resource's own types file,
	// in the SAME directory, declaring the shared Observation companion.
	httpSrc := `// Code generated by openapi2crd. DO NOT EDIT.
package v1alpha1

type ViewsOriginPoolWithWeightObservation struct {
	Cluster *string ` + "`json:\"cluster,omitempty\"`" + `
	EndpointSubsets *string ` + "`json:\"endpointSubsets,omitempty\"`" + `
	Pool *string ` + "`json:\"pool,omitempty\"`" + `
	Priority *int64 ` + "`json:\"priority,omitempty\"`" + `
	Weight *int64 ` + "`json:\"weight,omitempty\"`" + `
}
`
	writeFixtureInDir(t, dir, "zz_http_loadbalancers_types.go", httpSrc)

	fields, err := ParseGoTypes(tcpPath, "TCPLoadBalancer")
	if err != nil {
		t.Fatalf("ParseGoTypes: %v", err)
	}

	tests := []manifest.UpdateTest{
		{
			Field: "originPoolsWeights",
			Value: []interface{}{
				map[string]interface{}{
					"poolRef": map[string]interface{}{"name": "example-origin-pool"},
					"weight":  float64(1),
				},
			},
		},
	}

	findings := CheckObservability(tcpPath, fields, tests)
	if len(findings) != 1 {
		t.Fatalf("got %d findings, want 1 (poolRef resolved via the zz_http_loadbalancers_types.go sibling): %+v", len(findings), findings)
	}
	if findings[0].Field != "originPoolsWeights" {
		t.Errorf("Field = %q, want originPoolsWeights", findings[0].Field)
	}
	if len(findings[0].Keys) != 1 || findings[0].Keys[0] != "poolRef" {
		t.Errorf("Keys = %v, want [poolRef]", findings[0].Keys)
	}
}

// TestCheckObservabilitySplitFileObservationUnresolvedWhenNoSiblingDeclaresIt
// confirms the sibling-file fallback still reports "unresolvable" — not a
// false negative masquerading as a match — when NO file in the directory
// (primary or sibling) declares the Observation companion at all.
func TestCheckObservabilitySplitFileObservationUnresolvedWhenNoSiblingDeclaresIt(t *testing.T) {
	dir := t.TempDir()

	primarySrc := `// Code generated by openapi2crd. DO NOT EDIT.
package v1alpha1

type OrphanWidget struct {
	Label *string ` + "`json:\"label,omitempty\"`" + `
}

type OrphanParameters struct {
	Widget *OrphanWidget ` + "`json:\"widget,omitempty\"`" + `
}
`
	primaryPath := writeFixtureInDir(t, dir, "zz_orphan_types.go", primarySrc)

	// A sibling exists in the same directory, but declares nothing related
	// to OrphanWidgetObservation.
	siblingSrc := `// Code generated by openapi2crd. DO NOT EDIT.
package v1alpha1

type UnrelatedParameters struct {
	Name *string ` + "`json:\"name,omitempty\"`" + `
}
`
	writeFixtureInDir(t, dir, "zz_unrelated_types.go", siblingSrc)

	fields, err := ParseGoTypes(primaryPath, "Orphan")
	if err != nil {
		t.Fatalf("ParseGoTypes: %v", err)
	}

	tests := []manifest.UpdateTest{
		{Field: "widget", Value: map[string]interface{}{"label": "updated"}},
	}

	findings := CheckObservability(primaryPath, fields, tests)
	if len(findings) != 0 {
		t.Errorf("got %d findings, want 0 when no file (primary or sibling) declares OrphanWidgetObservation: %+v", len(findings), findings)
	}
}

// writeFixtureInDir writes contents to name inside dir (unlike writeFixture,
// which always allocates a fresh t.TempDir() per call) — used when a test
// needs two or more fixture files to coexist as siblings in the SAME
// directory, the shape resolveInSiblingTypesFiles searches.
func writeFixtureInDir(t *testing.T, dir, name, contents string) string {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte(contents), 0o600); err != nil {
		t.Fatalf("writing fixture %s: %v", name, err)
	}
	return path
}

// TestStructElemType covers the Go-type-string classifier in isolation: the
// []/* wrapper stripping, and the builtin/cross-package/map exclusions.
func TestStructElemType(t *testing.T) {
	cases := map[string]struct {
		reason   string
		goType   string
		wantName string
		wantOK   bool
	}{
		"SliceOfLocalStruct": {
			reason:   "a []LocalStruct field resolves to LocalStruct",
			goType:   "[]GadgetOwnerRef",
			wantName: "GadgetOwnerRef",
			wantOK:   true,
		},
		"PointerToLocalStruct": {
			reason:   "a *LocalStruct field resolves to LocalStruct",
			goType:   "*GadgetOwnerRef",
			wantName: "GadgetOwnerRef",
			wantOK:   true,
		},
		"PlainString": {
			reason:   "a builtin scalar (lowercase) is never a resolvable struct",
			goType:   "string",
			wantName: "",
			wantOK:   false,
		},
		"PointerString": {
			reason:   "*string strips to the builtin scalar string, still not resolvable",
			goType:   "*string",
			wantName: "",
			wantOK:   false,
		},
		"SliceOfString": {
			reason:   "[]string strips to the builtin scalar string, still not resolvable",
			goType:   "[]string",
			wantName: "",
			wantOK:   false,
		},
		"CrossPackageType": {
			reason:   "a dotted cross-package type cannot be inspected locally",
			goType:   "*xpv2.NamespacedReference",
			wantName: "",
			wantOK:   false,
		},
		"MapType": {
			reason:   "a map's keys are data, not a fixed struct shape",
			goType:   "map[string]string",
			wantName: "",
			wantOK:   false,
		},
		"Empty": {
			reason:   "an empty GoType (e.g. an unpopulated FieldInfo literal in a test) resolves to nothing",
			goType:   "",
			wantName: "",
			wantOK:   false,
		},
	}

	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			gotName, gotOK := structElemType(tc.goType)
			if gotName != tc.wantName || gotOK != tc.wantOK {
				t.Errorf("%s: structElemType(%q) = (%q, %v), want (%q, %v)",
					tc.reason, tc.goType, gotName, gotOK, tc.wantName, tc.wantOK)
			}
		})
	}
}
