package validator

import (
	"path/filepath"
	"reflect"
	"sort"
	"testing"

	"github.com/kaessert/crossplane-update-tester/internal/manifest"
)

// serverEchoControllerSrc mirrors the real provider-f5xc shape this check
// exists for (internal/controller/httploadbalancer/httploadbalancer.go):
// two go-cmp Transformer registrations, each naming a "clearServerDefaulted"
// function that nils out one field of a hand-written wire-shape struct when
// it matches the value the backend echoes back for every element the caller
// never set one for.
const serverEchoControllerSrc = `// Code generated. DO NOT EDIT BY HAND.
package httploadbalancer

import "github.com/google/go-cmp/cmp"

// apiHeaderMatcherType mirrors the wire schema's header matcher shape.
type apiHeaderMatcherType struct {
	Exact       *string ` + "`json:\"exact,omitempty\"`" + `
	InvertMatch *bool   ` + "`json:\"invert_match,omitempty\"`" + `
	Name        *string ` + "`json:\"name,omitempty\"`" + `
	Presence    *bool   ` + "`json:\"presence,omitempty\"`" + `
	Regex       *string ` + "`json:\"regex,omitempty\"`" + `
}

var normalizeHeaderMatcherInvertMatch = cmp.Transformer("normalizeHeaderMatcherInvertMatch", clearServerDefaultedInvertMatch)

// clearServerDefaultedInvertMatch clears InvertMatch when it points at
// false, mirroring the F5 XC API's behaviour of echoing invert_match: false
// on every header matcher element the caller never set one for.
func clearServerDefaultedInvertMatch(h apiHeaderMatcherType) apiHeaderMatcherType {
	if h.InvertMatch == nil || *h.InvertMatch {
		return h
	}
	h.InvertMatch = nil
	return h
}

// apiMessageMeta mirrors the wire schema's message-meta shape.
type apiMessageMeta struct {
	Description *string ` + "`json:\"description,omitempty\"`" + `
	Name        *string ` + "`json:\"name,omitempty\"`" + `
}

var normalizeMessageMetaDescription = cmp.Transformer("normalizeMessageMetaDescription", clearServerDefaultedDescription)

// clearServerDefaultedDescription clears Description when it points at "",
// mirroring the API's echoed empty-string description.
func clearServerDefaultedDescription(m *apiMessageMeta) *apiMessageMeta {
	if m == nil || m.Description == nil || *m.Description != "" {
		return m
	}
	out := *m
	out.Description = nil
	return &out
}
`

// serverEchoTypesSrc mirrors the real generated shape: BlockedClients
// nests httpHeader.headers[].invertMatch three levels deep, and reuses the
// SAME element type (CommonWafSimpleClientSrcRule) for both the Parameters
// and Observation sides with no separate "...Observation" companion —
// confirmed in provider-f5xc's zz_http_loadbalancers_types.go. TlsCert is
// an unrelated sibling field carrying its own "Description" field, on a
// struct shape that does NOT also carry "Name" — the case this check must
// NOT confuse with apiMessageMeta's Description.
const serverEchoTypesSrc = `// Code generated by openapi2crd. DO NOT EDIT.
package v1alpha1

type IoschemaHeaderMatcherType struct {
	Exact       *string ` + "`json:\"exact,omitempty\"`" + `
	InvertMatch *bool   ` + "`json:\"invertMatch,omitempty\"`" + `
	Name        *string ` + "`json:\"name,omitempty\"`" + `
	Presence    *bool   ` + "`json:\"presence,omitempty\"`" + `
	Regex       *string ` + "`json:\"regex,omitempty\"`" + `
}

type CommonWafHTTPHeaderMatcherList struct {
	Headers []IoschemaHeaderMatcherType ` + "`json:\"headers\"`" + `
}

type SchemaMessageMetaType struct {
	Description *string ` + "`json:\"description,omitempty\"`" + `
	Name        *string ` + "`json:\"name,omitempty\"`" + `
}

type SchemaTlsCertificateType struct {
	CertificateUrl *string ` + "`json:\"certificateUrl,omitempty\"`" + `
	Description    *string ` + "`json:\"description,omitempty\"`" + `
	Disable        *bool   ` + "`json:\"disable,omitempty\"`" + `
}

type CommonWafSimpleClientSrcRule struct {
	HttpHeader *CommonWafHTTPHeaderMatcherList ` + "`json:\"httpHeader,omitempty\"`" + `
	Metadata   *SchemaMessageMetaType          ` + "`json:\"metadata,omitempty\"`" + `
	TlsCert    *SchemaTlsCertificateType       ` + "`json:\"tlsCert,omitempty\"`" + `
}

// Widget/WidgetObservation is a distinct top-level shape from
// CommonWafSimpleClientSrcRule: its Parameters- and Observation-side
// structs are genuinely DIFFERENT types (Widget carries an Extra field the
// Observation companion does not), so resolving "widget" exercises the
// "<elemType>Observation" companion-preferred branch of
// resolveTypeFieldsForWalk instead of the bare-name fallback blockedClients
// exercises.
type Widget struct {
	Metadata *SchemaMessageMetaType ` + "`json:\"metadata,omitempty\"`" + `
	Extra    *string                ` + "`json:\"extra,omitempty\"`" + `
}

type WidgetObservation struct {
	Metadata *SchemaMessageMetaType ` + "`json:\"metadata,omitempty\"`" + `
}

type HttpLoadbalancerParameters struct {
	BlockedClients []CommonWafSimpleClientSrcRule ` + "`json:\"blockedClients\"`" + `
	Widget         *Widget                        ` + "`json:\"widget,omitempty\"`" + `
}
`

const kindHTTPLoadbalancer = "HttpLoadbalancer"

// serverEchoFixture writes both the types and controller fixtures to
// separate directories — mirroring apis/ vs internal/controller/ — and
// returns the types path, the parsed Parameters fields, and the controller
// directory.
func serverEchoFixture(t *testing.T) (typesPath string, fields []FieldInfo, controllerDir string) {
	t.Helper()
	typesPath = writeFixture(t, "zz_http_loadbalancers_types.go", serverEchoTypesSrc)
	fields, err := ParseGoTypes(typesPath, kindHTTPLoadbalancer)
	if err != nil {
		t.Fatalf("ParseGoTypes: %v", err)
	}

	controllerDir = t.TempDir()
	writeFixtureInDir(t, controllerDir, "httploadbalancer.go", serverEchoControllerSrc)

	return typesPath, fields, controllerDir
}

// blockedClientsHeader builds one blockedClients element's httpHeader.headers[0]
// object, optionally including invertMatch.
func blockedClientsHeader(withInvertMatch bool) map[string]interface{} {
	header := map[string]interface{}{"name": "X-Test-Header", "exact": "blocked-value"}
	if withInvertMatch {
		header["invertMatch"] = false
	}
	return map[string]interface{}{
		"httpHeader": map[string]interface{}{
			"headers": []interface{}{header},
		},
	}
}

// TestCheckServerEchoedExpectationsFlagsMissingNestedMember reproduces the
// motivating case verbatim: provider-f5xc's http-loadbalancer.yaml
// blockedClients entry, expect[0].httpHeader.headers[0] = {name, exact},
// missing the server-echoed invertMatch three levels deep.
func TestCheckServerEchoedExpectationsFlagsMissingNestedMember(t *testing.T) {
	typesPath, fields, controllerDir := serverEchoFixture(t)

	m := &manifest.Manifest{
		Kind: kindHTTPLoadbalancer,
		Tests: []manifest.UpdateTest{
			{
				Field: "blockedClients",
				Value: []interface{}{blockedClientsHeader(false)},
			},
		},
	}

	findings, err := CheckServerEchoedExpectations(typesPath, fields, m, controllerDir)
	if err != nil {
		t.Fatalf("CheckServerEchoedExpectations: %v", err)
	}
	if len(findings) != 1 {
		t.Fatalf("got %d findings, want 1: %+v", len(findings), findings)
	}
	if findings[0].Field != "blockedClients" {
		t.Errorf("Field = %q, want blockedClients", findings[0].Field)
	}
	if len(findings[0].Keys) != 1 || findings[0].Keys[0] != "invertMatch" {
		t.Errorf("Keys = %v, want [invertMatch]", findings[0].Keys)
	}
}

// TestCheckServerEchoedExpectationsCorrectedBlockNotFlagged confirms the
// exact remedy the finding names — adding invertMatch: false — clears the
// finding for the identical entry.
func TestCheckServerEchoedExpectationsCorrectedBlockNotFlagged(t *testing.T) {
	typesPath, fields, controllerDir := serverEchoFixture(t)

	m := &manifest.Manifest{
		Kind: kindHTTPLoadbalancer,
		Tests: []manifest.UpdateTest{
			{
				Field: "blockedClients",
				Value: []interface{}{blockedClientsHeader(true)},
			},
		},
	}

	findings, err := CheckServerEchoedExpectations(typesPath, fields, m, controllerDir)
	if err != nil {
		t.Fatalf("CheckServerEchoedExpectations: %v", err)
	}
	if len(findings) != 0 {
		t.Errorf("got %d findings, want 0 (invertMatch: false already named): %+v", len(findings), findings)
	}
}

// TestCheckServerEchoedExpectationsDescriptionAlreadyNamedNotFlagged pins
// the sibling AC: the existing metadata.description: "" expectations
// already correctly name the echoed member and must not be flagged.
func TestCheckServerEchoedExpectationsDescriptionAlreadyNamedNotFlagged(t *testing.T) {
	typesPath, fields, controllerDir := serverEchoFixture(t)

	entry := blockedClientsHeader(true)
	entry["metadata"] = map[string]interface{}{"description": "", "name": "rule-1"}

	m := &manifest.Manifest{
		Kind: kindHTTPLoadbalancer,
		Tests: []manifest.UpdateTest{
			{Field: "blockedClients", Value: []interface{}{entry}},
		},
	}

	findings, err := CheckServerEchoedExpectations(typesPath, fields, m, controllerDir)
	if err != nil {
		t.Fatalf("CheckServerEchoedExpectations: %v", err)
	}
	if len(findings) != 0 {
		t.Errorf("got %d findings, want 0 (description already named): %+v", len(findings), findings)
	}
}

// TestCheckServerEchoedExpectationsMissingDescriptionFlagged confirms the
// metadata.description sibling of the invertMatch case is caught the same
// way when it genuinely is missing (not just when invertMatch is missing).
func TestCheckServerEchoedExpectationsMissingDescriptionFlagged(t *testing.T) {
	typesPath, fields, controllerDir := serverEchoFixture(t)

	entry := blockedClientsHeader(true)
	entry["metadata"] = map[string]interface{}{"name": "rule-1"} // description omitted

	m := &manifest.Manifest{
		Kind: kindHTTPLoadbalancer,
		Tests: []manifest.UpdateTest{
			{Field: "blockedClients", Value: []interface{}{entry}},
		},
	}

	findings, err := CheckServerEchoedExpectations(typesPath, fields, m, controllerDir)
	if err != nil {
		t.Fatalf("CheckServerEchoedExpectations: %v", err)
	}
	if len(findings) != 1 || len(findings[0].Keys) != 1 || findings[0].Keys[0] != "description" {
		t.Fatalf("findings = %+v, want a single description finding", findings)
	}
}

// TestCheckServerEchoedExpectationsUnrelatedDescriptionFieldNotFlagged
// confirms the structural-fingerprint match: tlsCert.description is a
// DIFFERENT struct shape (SchemaTlsCertificateType lacks apiMessageMeta's
// "Name" field entirely) and must never be confused with the message-meta
// echo, even though the leaf JSON key name is identical.
func TestCheckServerEchoedExpectationsUnrelatedDescriptionFieldNotFlagged(t *testing.T) {
	typesPath, fields, controllerDir := serverEchoFixture(t)

	entry := blockedClientsHeader(true)
	entry["tlsCert"] = map[string]interface{}{"certificateUrl": "string:///cert"} // description omitted

	m := &manifest.Manifest{
		Kind: kindHTTPLoadbalancer,
		Tests: []manifest.UpdateTest{
			{Field: "blockedClients", Value: []interface{}{entry}},
		},
	}

	findings, err := CheckServerEchoedExpectations(typesPath, fields, m, controllerDir)
	if err != nil {
		t.Fatalf("CheckServerEchoedExpectations: %v", err)
	}
	if len(findings) != 0 {
		t.Errorf("got %d findings, want 0 (tlsCert.description is not the echoed message-meta shape): %+v", len(findings), findings)
	}
}

// TestCheckServerEchoedExpectationsObservationCompanionResolved confirms a
// top-level field whose Parameters- and Observation-side shapes genuinely
// differ (an "<elemType>Observation" companion exists, unlike blockedClients)
// still resolves through that companion and flags a missing echoed member.
func TestCheckServerEchoedExpectationsObservationCompanionResolved(t *testing.T) {
	typesPath, fields, controllerDir := serverEchoFixture(t)

	m := &manifest.Manifest{
		Kind: kindHTTPLoadbalancer,
		Tests: []manifest.UpdateTest{
			{
				Field: "widget",
				Value: map[string]interface{}{"metadata": map[string]interface{}{"name": "rule-1"}},
			},
		},
	}

	findings, err := CheckServerEchoedExpectations(typesPath, fields, m, controllerDir)
	if err != nil {
		t.Fatalf("CheckServerEchoedExpectations: %v", err)
	}
	if len(findings) != 1 || len(findings[0].Keys) != 1 || findings[0].Keys[0] != "description" {
		t.Fatalf("findings = %+v, want a single description finding via the WidgetObservation companion", findings)
	}
}

// TestCheckServerEchoedExpectationsNoControllerDirDisabled confirms the
// feature is inert (no findings, no error) when the caller passes no
// controller directory — the current default until every Makefile wiring
// is updated to pass one.
func TestCheckServerEchoedExpectationsNoControllerDirDisabled(t *testing.T) {
	typesPath, fields, _ := serverEchoFixture(t)

	m := &manifest.Manifest{
		Kind: kindHTTPLoadbalancer,
		Tests: []manifest.UpdateTest{
			{Field: "blockedClients", Value: []interface{}{blockedClientsHeader(false)}},
		},
	}

	findings, err := CheckServerEchoedExpectations(typesPath, fields, m, "")
	if err != nil {
		t.Fatalf("CheckServerEchoedExpectations: %v", err)
	}
	if len(findings) != 0 {
		t.Errorf("got %d findings, want 0 when controllerDir is empty: %+v", len(findings), findings)
	}
}

// TestCheckServerEchoedExpectationsSkipEntryNotFlagged confirms a skip:
// entry is never flagged, matching every other check in this package.
func TestCheckServerEchoedExpectationsSkipEntryNotFlagged(t *testing.T) {
	typesPath, fields, controllerDir := serverEchoFixture(t)

	m := &manifest.Manifest{
		Kind: kindHTTPLoadbalancer,
		Tests: []manifest.UpdateTest{
			{
				Field: "blockedClients",
				Skip:  manifest.LegacySkip("not exercised in this example"),
				Value: []interface{}{blockedClientsHeader(false)},
			},
		},
	}

	findings, err := CheckServerEchoedExpectations(typesPath, fields, m, controllerDir)
	if err != nil {
		t.Fatalf("CheckServerEchoedExpectations: %v", err)
	}
	if len(findings) != 0 {
		t.Errorf("got %d findings, want 0 for a skip: entry: %+v", len(findings), findings)
	}
}

// TestCheckServerEchoedExpectationsControllerDirWithNoTransformersInert
// confirms a controller package with no cmp.Transformer registration at all
// (every other resource in the fleet, today) returns zero findings and no
// error rather than a false positive or a spurious failure.
func TestCheckServerEchoedExpectationsControllerDirWithNoTransformersInert(t *testing.T) {
	typesPath, fields, _ := serverEchoFixture(t)

	controllerDir := t.TempDir()
	writeFixtureInDir(t, controllerDir, "originpool.go", `package originpool

func reconcile() {}
`)

	m := &manifest.Manifest{
		Kind: kindHTTPLoadbalancer,
		Tests: []manifest.UpdateTest{
			{Field: "blockedClients", Value: []interface{}{blockedClientsHeader(false)}},
		},
	}

	findings, err := CheckServerEchoedExpectations(typesPath, fields, m, controllerDir)
	if err != nil {
		t.Fatalf("CheckServerEchoedExpectations: %v", err)
	}
	if len(findings) != 0 {
		t.Errorf("got %d findings, want 0 when the controller registers no transformer: %+v", len(findings), findings)
	}
}

// TestCheckServerEchoedExpectationsMissingControllerDirErrors confirms a
// --controller-dir naming a directory that does not exist is a hard error —
// silently proceeding would validate against no normalizers at all and
// report a clean pass that proves nothing.
func TestCheckServerEchoedExpectationsMissingControllerDirErrors(t *testing.T) {
	typesPath, fields, _ := serverEchoFixture(t)

	m := &manifest.Manifest{Kind: kindHTTPLoadbalancer}

	_, err := CheckServerEchoedExpectations(typesPath, fields, m, filepath.Join(t.TempDir(), "does-not-exist"))
	if err == nil {
		t.Error("got nil error for a nonexistent controller-dir, want an error")
	}
}

// TestDiscoverServerEchoedMembers covers the discovery step in isolation:
// both registrations resolve to their struct's full field-name set plus the
// one field each clears.
func TestDiscoverServerEchoedMembers(t *testing.T) {
	dir := t.TempDir()
	writeFixtureInDir(t, dir, "httploadbalancer.go", serverEchoControllerSrc)

	members, err := discoverServerEchoedMembers(dir)
	if err != nil {
		t.Fatalf("discoverServerEchoedMembers: %v", err)
	}
	if len(members) != 2 {
		t.Fatalf("got %d members, want 2: %+v", len(members), members)
	}

	byEchoedField := make(map[string]ServerEchoedMember, len(members))
	for _, m := range members {
		byEchoedField[m.EchoedField] = m
	}

	invertMatch, ok := byEchoedField["InvertMatch"]
	if !ok {
		t.Fatalf("no member for InvertMatch: %+v", members)
	}
	wantHeaderFields := []string{"Exact", "InvertMatch", "Name", "Presence", "Regex"}
	sort.Strings(invertMatch.StructFieldNames)
	if !reflect.DeepEqual(invertMatch.StructFieldNames, wantHeaderFields) {
		t.Errorf("InvertMatch member StructFieldNames = %v, want %v", invertMatch.StructFieldNames, wantHeaderFields)
	}

	description, ok := byEchoedField["Description"]
	if !ok {
		t.Fatalf("no member for Description: %+v", members)
	}
	wantMetaFields := []string{"Description", "Name"}
	sort.Strings(description.StructFieldNames)
	if !reflect.DeepEqual(description.StructFieldNames, wantMetaFields) {
		t.Errorf("Description member StructFieldNames = %v, want %v", description.StructFieldNames, wantMetaFields)
	}
}

// TestDiscoverServerEchoedMembersNoTransformerCalls confirms a package with
// no cmp.Transformer registration at all returns an empty, non-error
// result.
func TestDiscoverServerEchoedMembersNoTransformerCalls(t *testing.T) {
	dir := t.TempDir()
	writeFixtureInDir(t, dir, "plain.go", `package plain

func reconcile() {}
`)

	members, err := discoverServerEchoedMembers(dir)
	if err != nil {
		t.Fatalf("discoverServerEchoedMembers: %v", err)
	}
	if len(members) != 0 {
		t.Errorf("got %d members, want 0: %+v", len(members), members)
	}
}

// TestMatchServerEchoedMembersRequiresFullFieldSet covers the matcher in
// isolation: a candidate struct missing even one of a member's declared
// StructFieldNames is never matched, however many of the OTHER fields
// (including the echoed field's own name) it does share.
func TestMatchServerEchoedMembersRequiresFullFieldSet(t *testing.T) {
	members := []ServerEchoedMember{
		{StructFieldNames: []string{"Description", "Name"}, EchoedField: "Description"},
	}

	cases := map[string]struct {
		reason     string
		candidate  []FieldInfo
		wantEchoed bool
	}{
		"ExactFieldSetMatches": {
			reason:     "candidate declares exactly Description and Name",
			candidate:  []FieldInfo{{GoName: "Description"}, {GoName: "Name"}},
			wantEchoed: true,
		},
		"SupersetFieldSetMatches": {
			reason:     "candidate declares Description and Name plus CRD-only extras",
			candidate:  []FieldInfo{{GoName: "Description"}, {GoName: "Name"}, {GoName: "CertificateUrl"}},
			wantEchoed: true,
		},
		"MissingDeclaredFieldNeverMatches": {
			reason:     "candidate has Description but lacks Name — a different struct shape entirely",
			candidate:  []FieldInfo{{GoName: "Description"}, {GoName: "CertificateUrl"}},
			wantEchoed: false,
		},
	}

	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			got := matchServerEchoedMembers(tc.candidate, members)
			if got["Description"] != tc.wantEchoed {
				t.Errorf("%s: matchServerEchoedMembers()[\"Description\"] = %v, want %v", tc.reason, got["Description"], tc.wantEchoed)
			}
		})
	}
}

// TestPrintServerEchoedExpectationsDoesNotPanic is a smoke test for the
// output formatter, matching the convention of every other Print* function
// in this package.
func TestPrintServerEchoedExpectationsDoesNotPanic(t *testing.T) {
	PrintServerEchoedExpectations(nil)
	PrintServerEchoedExpectations([]ServerEchoedExpectationFinding{
		{Field: "blockedClients", Keys: []string{"invertMatch"}},
	})
}
